const noEffect = '(No Effect)';

const types = {
  normal: {
    strongAgainst: [],
    weakAgainst: ['Rock', 'Steel', `Ghost ${noEffect}`],
    resistantTo: [`Ghost ${noEffect}`],
    weakTo: ['Fighting'],
    color: '#c0c1c4',
    text: 'black',
  },
  fighting: {
    strongAgainst: ['Normal', 'Rock', 'Steel', 'Ice', 'Dark'],
    weakAgainst: ['Flying', 'Poison', 'Bug', 'Psychic', 'Fairy', `Ghost ${noEffect}`],
    resistantTo: ['Rock', 'Bug', 'Dark'],
    weakTo: ['Flying', 'Psychic', 'Fairy'],
    color: '#ed9932',
    text: 'black',
  },
  flying: {
    strongAgainst: ['Fighting', 'Bug', 'Grass'],
    weakAgainst: ['Rock', 'Steel', 'Electric'],
    resistantTo: ['Fighting', 'Bug', 'Grass', `Ground ${noEffect}`],
    weakTo: ['Rock', 'Electric', 'Ice'],
    color: '#abe6ff',
    text: 'black',
  },
  poison: {
    strongAgainst: ['Grass', 'Fairy'],
    weakAgainst: ['Poison', 'Ground', 'Rock', 'Ghost', `Steel ${noEffect}`],
    resistantTo: ['Fighting', 'Poison', 'Grass', 'Fairy'],
    weakTo: ['Ground', 'Psychic'],
    color: '#c180ff',
    text: 'black',
  },
  ground: {
    strongAgainst: ['Poison', 'Rock', 'Steel', 'Fire', 'Electric'],
    weakAgainst: ['Bug', 'Grass', `Flying ${noEffect}`],
    resistantTo: ['Poison', 'Rock', `Electric ${noEffect}`],
    weakTo: ['Water', 'Grass', 'Ice'],
    color: '#b3ab9d',
    text: 'black',
  },
  rock: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#857863',
    text: 'black',
  },
  bug: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#68825a',
    text: 'black',
  },
  ghost: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#5c4b70',
    text: 'black',
  },
  steel: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#787878',
    text: 'black',
  },
  fire: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#de2810',
    text: 'black',
  },
  water: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#0e24e8',
    text: 'black',
  },
  grass: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#0ee815',
    text: 'black',
  },
  electric: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#edff2b',
    text: 'black',
  },
  psychic: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#fa20d6',
    text: 'black',
  },
  ice: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#20faf3',
    text: 'black',
  },
  dragon: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#6600f5',
    text: 'black',
  },
  dark: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#353436',
    text: 'black',
  },
  fairy: {
    strongAgainst: [],
    weakAgainst: [],
    resistantTo: [],
    weakTo: [],
    color: '#ffc4fb',
    text: 'black',
  },
}

export default types;