const noEffect = '(No Effect)';

const types = {
  normal: {
    strongAgainst: [],
    weakAgainst: ['Rock', 'Steel', `Ghost ${noEffect}`],
    resistantTo: [`Ghost ${noEffect}`],
    weakTo: ['Fighting'],
    color: '#c0c1c4',
    text: 'black',
  },
  fighting: {
    strongAgainst: ['Normal', 'Rock', 'Steel', 'Ice', 'Dark'],
    weakAgainst: ['Flying', 'Poison', 'Bug', 'Psychic', 'Fairy', `Ghost ${noEffect}`],
    resistantTo: ['Rock', 'Bug', 'Dark'],
    weakTo: ['Flying', 'Psychic', 'Fairy'],
    color: '#ed9932',
    text: 'black',
  },
  flying: {
    strongAgainst: ['Fighting', 'Bug', 'Grass'],
    weakAgainst: ['Rock', 'Steel', 'Electric'],
    resistantTo: ['Fighting', 'Bug', 'Grass', `Ground ${noEffect}`],
    weakTo: ['Rock', 'Electric', 'Ice'],
    color: '#abe6ff',
    text: 'black',
  },
  poison: {
    strongAgainst: ['Grass', 'Fairy'],
    weakAgainst: ['Poison', 'Ground', 'Rock', 'Ghost', `Steel ${noEffect}`],
    resistantTo: ['Fighting', 'Poison', 'Grass', 'Fairy'],
    weakTo: ['Ground', 'Psychic'],
    color: '#c180ff',
    text: 'black',
  },
  ground: {
    strongAgainst: ['Poison', 'Rock', 'Steel', 'Fire', 'Electric'],
    weakAgainst: ['Bug', 'Grass', `Flying ${noEffect}`],
    resistantTo: ['Poison', 'Rock', `Electric ${noEffect}`],
    weakTo: ['Water', 'Grass', 'Ice'],
    color: '#b3ab9d',
    text: 'black',
  },
  rock: {
    strongAgainst: ['Flying', 'Bug', 'Fire', 'Ice'],
    weakAgainst: ['Fighting', 'Ground', 'Steel'],
    resistantTo: ['Normal', 'Flying', 'Poison', 'Fire'],
    weakTo: ['Fighting', 'Ground', 'Steel', 'Water', 'Grass'],
    color: '#857863',
    text: 'black',
  },
  bug: {
    strongAgainst: ['Grass', 'Psychic', 'Dark'],
    weakAgainst: ['Fighting', 'Flying', 'Poison', 'Ghost', 'Steel', 'Fire', 'Fairy'],
    resistantTo: ['Fighting', 'Ground', 'Grass'],
    weakTo: ['Flying', 'Rock', 'Fire'],
    color: '#68825a',
    text: 'black',
  },
  ghost: {
    strongAgainst: ['Ghost', 'Psychic'],
    weakAgainst: [`Normal ${noEffect}`, 'Dark'],
    resistantTo: ['Poison', 'Bug', `Normal ${noEffect}`, `Fighting ${noEffect}`],
    weakTo: ['Ghost', 'Dark'],
    color: '#5c4b70',
    text: 'white',
  },
  steel: {
    strongAgainst: ['Rock', 'Ice', 'Fairy'],
    weakAgainst: ['Steel', 'Fire', 'Water', 'Electric'],
    resistantTo: ['Normal', 'Flying', 'Rock', 'Bug', 'Steel', 'Grass', 'Psychic', 'Ice', 'Dragon', 'Fairy', `Poison ${noEffect}`],
    weakTo: ['Fighting', 'Ground', 'Fire'],
    color: '#787878',
    text: 'black',
  },
  fire: {
    strongAgainst: ['Bug', 'Steel', 'Grass', 'Ice'],
    weakAgainst: ['Rock', 'Fire', 'Water', 'Dragon'],
    resistantTo: ['Bug', 'Steel', 'Fire', 'Grass', 'Ice'],
    weakTo: ['Ground', 'Rock', 'Water'],
    color: '#de2810',
    text: 'black',
  },
  water: {
    strongAgainst: ['Ground', 'Rock', 'Fire'],
    weakAgainst: ['Water', 'Grass', 'Dragon'],
    resistantTo: ['Steel', 'Fire', 'Water', 'Ice'],
    weakTo: ['Grass', 'Electric'],
    color: '#0e24e8',
    text: 'white',
  },
  grass: {
    strongAgainst: ['Ground', 'Rock', 'Water'],
    weakAgainst: ['Flying', 'Poison', 'Bug', 'Steel', 'Fire', 'Grass', 'Dragon'],
    resistantTo: ['Ground', 'Water', 'Grass', 'Electric'],
    weakTo: ['Flying', 'Poison', 'Bug', 'Fire', 'Ice'],
    color: '#0ee815',
    text: 'black',
  },
  electric: {
    strongAgainst: ['Flying', 'Water'],
    weakAgainst: ['Grass', 'Electric', 'Dragon', `Ground ${noEffect}`],
    resistantTo: ['Flying', 'Steel', 'Electric'],
    weakTo: ['Ground'],
    color: '#edff2b',
    text: 'black',
  },
  psychic: {
    strongAgainst: ['Fighting', 'Poison'],
    weakAgainst: ['Steel', 'Psychic', `Dark ${noEffect}`],
    resistantTo: ['Fighting', 'Psychic'],
    weakTo: ['Bug', 'Ghost', 'Dark'],
    color: '#fa20d6',
    text: 'black',
  },
  ice: {
    strongAgainst: ['Flying', 'Ground', 'Grass', 'Dragon'],
    weakAgainst: ['Steel', 'Fire', 'Water', 'Ice'],
    resistantTo: ['Ice'],
    weakTo: ['Fighting', 'Rock', 'Steel', 'Fire'],
    color: '#20faf3',
    text: 'black',
  },
  dragon: {
    strongAgainst: ['Dragon'],
    weakAgainst: ['Steel', `Fairy ${noEffect}`],
    resistantTo: ['Fire', 'Water', 'Grass', 'Electric'],
    weakTo: ['Ice', 'Dragon', 'Fairy'],
    color: '#6600f5',
    text: 'white',
  },
  dark: {
    strongAgainst: ['Ghost', 'Psychic'],
    weakAgainst: ['Fighting', 'Dark', 'Fairy'],
    resistantTo: ['Ghost', 'Dark', `Psychic ${noEffect}`],
    weakTo: ['Fighting', 'Bug', 'Fairy'],
    color: '#353436',
    text: 'white',
  },
  fairy: {
    strongAgainst: ['Fighting', 'Dragon', 'Dark'],
    weakAgainst: ['Poison', 'Steel', 'Fire'],
    resistantTo: ['Fighting', 'Bug', 'Dark', `Dragon ${noEffect}`],
    weakTo: ['Poison', 'Steel'],
    color: '#ffc4fb',
    text: 'black',
  },
}

export default types;